### ISSUE TITLE
Gem in RubyGems is not the same as the commit that has 0.1.1 in the repository

### ISSUE THREAD

**Issue by belfazt** [fundamerica/trulioo#1]
The gem uploaded in RubyGems as version `0.1.1` is not the same as the one that the repo reflects

Fix is to use this in the Gemfile

```ruby
gem 'trulioo', '~> 0.1', git: 'https://github.com/fundamerica/trulioo.git', branch: 'master', ref: 'a9a2c17946ba6c491b051e3bee2e9a7e175571e6'
```

**Comment by invadervimdev** [comment]
Thanks for the notice, @belfazt. I've updated the RubyGems version. You can continue using that fix if you want the latest (not always tested) updates, but I'll be trying to keep the stable releases in the gem.
